services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-marketing-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Use this for development to avoid rebuilding the image for code changes
      # - ./app:/app
      # For production, use volume for the model only
      - ./app/catboost_model.cbm:/app/catboost_model.cbm
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge